language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4snapshot
          env: SKELETON_VERSION="^3.4"
        - php: 7.4snapshot
          env: SKELETON_VERSION="^4.4"
        - php: 7.4snapshot
          env: SKELETON_VERSION="^5.0"

before_install:
    - phpenv config-rm xdebug.ini || true
    - export SYMFONY_ENDPOINT=https://symfony.sh/r/github.com/symfony/recipes/${TRAVIS_PULL_REQUEST}
    - export PACKAGES=$(curl -s $SYMFONY_ENDPOINT | sed -En 's/.*composer req "([^"]+)".*/\1/p')

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" flex
    - cd flex

script:
    - composer req $(echo $PACKAGES)
