httplug:
    plugins:
        retry:
            retry: 1

    discovery:
        client: 'auto'

    clients:
        app:
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
                - header_defaults:
                    headers:
                        "X-Httplug": "This is just an example"
                - 'httplug.plugin.retry'
