ai:
    store:
        typesense:
            default:
                host: '%env(TYPESENSE_HOST)%'
                port: '%env(int:TYPESENSE_PORT)%'
                api_key: '%env(TYPESENSE_API_KEY)%'
