# config/packages/ai.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\AI\Agent\Toolbox\Tool\Clock: null

ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'

    agent:
        default:
            platform: 'ai.platform.openai'
            model: 'gpt-4o-mini'
            system_prompt: |
                You are a helpful assistant and you can provide the current date and time.
            tools:
                - 'Symfony\AI\Agent\Toolbox\Tool\Clock'
